import { useState } from 'react'
import { api, messageFromError } from '../services/api'
import { useLanguage } from '../context/LanguageContext'
type Staff = { id: string; displayName: string; mobileNumber: string; roles: string[]; hospitalIds: string[] }
export function StaffAccountControls({ hospitals }: { hospitals: { id: string; name: string }[] }) {
  const { text } = useLanguage()
  const [staff, setStaff] = useState<Staff[]>([]), [userId, setUserId] = useState(''), [hospitalId, setHospitalId] = useState('')
  const [verified, setVerified] = useState(false), [code, setCode] = useState(''), [busy, setBusy] = useState(false), [message, setMessage] = useState('')
  async function run(action: () => Promise<void>) { setBusy(true); setMessage(''); setCode(''); try { await action() } catch (e) { setMessage(messageFromError(e)) } finally { setBusy(false) } }
  async function load() { setStaff((await api.get<Staff[]>('/api/v1/auth/staff')).data) }
  return <section className="mt-8 border-t border-blue-100 pt-6"><h2 className="text-xl font-bold text-blue-950">{text('Existing staff access', 'मौजूदा स्टाफ की अनुमति')}</h2><button type="button" disabled={busy} onClick={() => void run(load)} className="my-4 rounded-xl border border-blue-200 px-4 py-2 text-sm font-semibold text-blue-700">{text('Load staff directory', 'स्टाफ सूची खोलें')}</button>
    <fieldset disabled={busy} className="grid gap-4"><label className="text-sm font-semibold">{text('Staff account', 'स्टाफ अकाउंट')}<select className="mt-2 w-full rounded-xl border border-blue-200 p-3" value={userId} onChange={e => { setUserId(e.target.value); setVerified(false); setCode('') }}><option value="">{text('Select staff', 'स्टाफ चुनें')}</option>{staff.map(s => <option key={s.id} value={s.id}>{s.displayName} · {s.mobileNumber} · {s.roles.join(', ')}</option>)}</select></label>
    {userId && <p className="break-all rounded-xl bg-blue-50 p-3 text-xs text-blue-900">ID: {userId}<br />{text('Assigned hospitals:', 'असाइन किए गए अस्पताल:')} {staff.find(s => s.id === userId)?.hospitalIds.map(id => hospitals.find(h => h.id === id)?.name ?? id).join(', ') || text('None', 'कोई नहीं')}</p>}
    <label className="text-sm font-semibold">{text('Hospital assignment', 'अस्पताल असाइनमेंट')}<select className="mt-2 w-full rounded-xl border border-blue-200 p-3" value={hospitalId} onChange={e => setHospitalId(e.target.value)}><option value="">{text('Choose hospital', 'अस्पताल चुनें')}</option>{hospitals.map(h => <option key={h.id} value={h.id}>{h.name}</option>)}</select></label>
    <div className="flex gap-3"><button type="button" disabled={!userId || !hospitalId} onClick={() => void run(async () => { await api.put(`/api/v1/auth/staff/${userId}/hospitals/${hospitalId}`); await load(); setMessage(text('Assignment saved.', 'असाइनमेंट सहेजा गया।')) })} className="rounded-xl bg-blue-600 px-4 py-2 text-sm font-semibold text-white disabled:opacity-40">{text('Assign hospital', 'अस्पताल असाइन करें')}</button><button type="button" disabled={!userId || !hospitalId} onClick={() => void run(async () => { await api.delete(`/api/v1/auth/staff/${userId}/hospitals/${hospitalId}`); await load(); setMessage(text('Explicit membership removed. A verified doctor profile remains a separate assignment.', 'स्पष्ट सदस्यता हटाई गई। सत्यापित डॉक्टर प्रोफ़ाइल अलग असाइनमेंट रहती है।')) })} className="rounded-xl border border-rose-200 px-4 py-2 text-sm text-rose-700 disabled:opacity-40">{text('Remove assignment', 'असाइनमेंट हटाएँ')}</button></div>
    <label className="mt-3 flex items-start gap-3 text-sm"><input type="checkbox" checked={verified} onChange={e => setVerified(e.target.checked)} />{text('I independently verified this person’s identity before issuing account recovery.', 'रिकवरी कोड देने से पहले मैंने इस व्यक्ति की पहचान स्वतंत्र रूप से सत्यापित की है।')}</label><button type="button" disabled={!verified || !userId} onClick={() => void run(async () => { const { data } = await api.post<{ code: string; expiresAt: string }>('/api/v1/auth/recovery-code', { userId, identityVerified: true }); setCode(data.code); setMessage(text('Share privately. Expires in 30 minutes; use once.', 'निजी रूप से दें। 30 मिनट में समाप्त; एक बार उपयोग।')); setVerified(false) })} className="rounded-xl border border-blue-200 px-4 py-3 text-sm font-semibold text-blue-700 disabled:opacity-40">{text('Issue recovery code', 'रिकवरी कोड दें')}</button></fieldset>
    {message && <p role="status" className="mt-4 rounded-xl bg-blue-50 p-3 text-sm">{message}</p>}{code && <code className="mt-3 block break-all rounded-xl bg-amber-50 p-4">{code}</code>}
  </section>
}
