In [2]:
import pandas as pd

comparison = pd.DataFrame(
    [
        {
            "dataset": "Original SmartCare OPD",
            "records": 5000,
            "task": "Wait-time regression",
            "best_model": "HistGradientBoosting",
            "MAE_minutes": 27.16,
            "RMSE_minutes": 40.92,
            "R2": 0.2186,
            "decision": "Prototype hybrid estimate",
        },
        {
            "dataset": "Appointment Scheduling",
            "records": 86032,
            "task": "Wait-time regression",
            "best_model": "HistGradientBoosting",
            "MAE_minutes": 28.63,
            "RMSE_minutes": 37.64,
            "R2": 0.1459,
            "decision": "Academic analysis only",
        },
        {
            "dataset": "Patient Flow",
            "records": 9216,
            "task": "Descriptive wait analysis",
            "best_model": "Not trained",
            "MAE_minutes": None,
            "RMSE_minutes": None,
            "R2": None,
            "decision": "Rejected: weak features/leakage",
        },
        {
            "dataset": "Appointment No-show",
            "records": 1878,
            "task": "Wait-time regression",
            "best_model": "HistGradientBoosting",
            "MAE_minutes": 46.37,
            "RMSE_minutes": 54.69,
            "R2": -0.1100,
            "decision": "Rejected",
        },
        {
            "dataset": "Simulated ER (cross-phase test)",
            "records": 500,
            "task": "Wait-time regression",
            "best_model": "Random Forest",
            "MAE_minutes": 45.92,
            "RMSE_minutes": 53.98,
            "R2": -4.3045,
            "decision": "Rejected: dataset shift",
        },
    ]
)

display(comparison)

,dataset,records,task,best_model,MAE_minutes,RMSE_minutes,R2,decision
0,Original SmartCare OPD,5000,Wait-time regression,HistGradientBoosting,27.16,40.92,0.2186,Prototype hybrid estimate
1,Appointment Scheduling,86032,Wait-time regression,HistGradientBoosting,28.63,37.64,0.1459,Academic analysis only
2,Patient Flow,9216,Descriptive wait analysis,Not trained,NaN,NaN,NaN,Rejected: weak features/leakage
3,Appointment No-show,1878,Wait-time regression,HistGradientBoosting,46.37,54.69,-0.1100,Rejected
4,Simulated ER (cross-phase test),500,Wait-time regression,Random Forest,45.92,53.98,-4.3045,Rejected: dataset shift


## Final Wait-Time Dataset Decision

Four additional datasets were evaluated for improving SmartCare's wait-time prediction.

The experiments showed that a large number of records does not guarantee a useful model. Some datasets lacked real queue predictors, some contained privacy or leakage risks, and the simulated ER model failed when evaluated after an operational intervention.

Therefore, none of the newly evaluated models will replace the existing SmartCare prototype model.

SmartCare will continue to use an explainable hybrid estimate combining:

- historical department and triage baseline,
- patients ahead,
- active doctors,
- average consultation duration,
- current doctor delay,
- occupancy and urgency adjustments.

The result will remain an indicative waiting-time range, not a guaranteed clinical appointment time.

No raw dataset, personal information, rejected model, or unreviewed experiment will be deployed.
	dataset	records	task	best_model	MAE_minutes	RMSE_minutes	R2	decision
0	Original SmartCare OPD	5000	Wait-time regression	HistGradientBoosting	27.16	40.92	0.2186	Prototype hybrid estimate
1	Appointment Scheduling	86032	Wait-time regression	HistGradientBoosting	28.63	37.64	0.1459	Academic analysis only
2	Patient Flow	9216	Descriptive wait analysis	Not trained	NaN	NaN	NaN	Rejected: weak features/leakage
3	Appointment No-show	1878	Wait-time regression	HistGradientBoosting	46.37	54.69	-0.1100	Rejected
4	Simulated ER (cross-phase test)	500	Wait-time regression	Random Forest	45.92	53.98	-4.3045	Rejected: dataset shift
