import {
  Building2, CalendarClock, ChevronRight, Filter, Hospital, IndianRupee,
  Landmark, MapPin, Search, ShieldAlert, Stethoscope, X,
} from 'lucide-react'
import { useEffect, useMemo, useState } from 'react'
import { Link } from 'react-router-dom'
import { indiaFacilities, indiaStatesAndUts, type FacilityOwnership, type IndiaFacility } from '../data/indiaFacilities'
import { projectDoctors } from '../data/projectDoctorProfiles'
import { recommendDepartment, type DepartmentRecommendation } from '../data/departmentRecommendation'

export function HospitalDirectoryPage() {
  const [state, setState] = useState('')
  const [ownership, setOwnership] = useState<FacilityOwnership | ''>('')
  const [search, setSearch] = useState('')
  const [pickerGroup, setPickerGroup] = useState<FacilityOwnership | null>(null)
  const [pickerSearch, setPickerSearch] = useState('')
  const [selected, setSelected] = useState<IndiaFacility | null>(null)
  const [symptoms, setSymptoms] = useState('')
  const [recommendation, setRecommendation] = useState<DepartmentRecommendation | null>(null)
  const visible = useMemo(() => indiaFacilities.filter((facility) => (!state || facility.state === state) && (!ownership || facility.ownership === ownership) && (!search || `${facility.name} ${facility.city} ${facility.state}`.toLowerCase().includes(search.toLowerCase()))), [ownership, search, state])
  const government = visible.filter((item) => item.ownership === 'GOVERNMENT')
  const privateFacilities = visible.filter((item) => item.ownership === 'PRIVATE')

  useEffect(() => {
    if (!pickerGroup) return
    const previousOverflow = document.body.style.overflow
    document.body.style.overflow = 'hidden'
    return () => { document.body.style.overflow = previousOverflow }
  }, [pickerGroup])

  function openPicker(group: FacilityOwnership) {
    setPickerGroup(group)
    setPickerSearch('')
    setSelected(visible.find((item) => item.ownership === group) ?? indiaFacilities.find((item) => item.ownership === group) ?? null)
  }

  const pickerFacilities = indiaFacilities.filter((facility) => facility.ownership === pickerGroup && (!state || facility.state === state) && (!pickerSearch || `${facility.name} ${facility.city} ${facility.state}`.toLowerCase().includes(pickerSearch.toLowerCase())))
  const doctors = selected ? projectDoctors(selected) : []
  const selectedFacilityIndex = selected ? indiaFacilities.indexOf(selected) : -1

  return <div className="min-h-screen bg-[#f5f8fc]">
    <section className="bg-[linear-gradient(120deg,#071b35,#164e7a_62%,#087f8c)] text-white"><div className="mx-auto grid max-w-7xl gap-8 px-4 py-12 sm:px-6 lg:grid-cols-[1fr_.75fr] lg:px-8 lg:py-16"><div><p className="text-xs font-black uppercase tracking-[.2em] text-cyan-200">India care directory · prototype</p><h1 className="mt-3 text-4xl font-black tracking-tight sm:text-5xl">Choose a hospital without leaving SmartCare</h1><p className="mt-4 max-w-3xl text-sm leading-7 text-blue-100/80 sm:text-base">Filter all 28 states and 8 union territories, open one scrollable hospital picker, and review its departments and demo doctor profiles inside this project.</p></div><div className="grid grid-cols-3 gap-3 self-end">{[[36, 'States & UTs'], [indiaFacilities.length, 'Prototype hospitals'], [2, 'Care groups']].map(([value, label]) => <div key={label} className="rounded-2xl border border-white/10 bg-white/10 p-4 text-center"><p className="text-3xl font-black">{value}</p><p className="mt-1 text-[11px] font-bold text-blue-100/70">{label}</p></div>)}</div></div></section>

    <main className="mx-auto max-w-7xl px-4 py-8 sm:px-6 lg:px-8 lg:py-10">
      <div className="rounded-3xl border border-amber-200 bg-amber-50 p-5 text-sm leading-6 text-amber-950"><div className="flex gap-3"><ShieldAlert className="mt-0.5 size-5 shrink-0 text-amber-700" /><div><strong>Project simulation data.</strong> Hospitals, doctors, fees, availability and follow-up policies on this screen demonstrate the SmartCare workflow. They are not live listings and do not redirect to third-party websites.</div></div></div>
      <section className="mt-6 rounded-3xl border border-cyan-200 bg-white p-5 shadow-sm sm:p-6">
        <p className="text-xs font-black uppercase tracking-[.18em] text-care-700">Explainable department guidance</p>
        <h2 className="mt-2 text-2xl font-black text-ink-950">Which department should I visit?</h2>
        <p className="mt-2 text-sm leading-6 text-slate-600">Describe the main symptom. SmartCare uses transparent routing rules to suggest a department—not a diagnosis.</p>
        <div className="mt-4 flex flex-col gap-3 sm:flex-row"><label className="sr-only" htmlFor="symptom-guidance">Main symptom</label><input id="symptom-guidance" value={symptoms} onChange={(event) => setSymptoms(event.target.value)} placeholder="e.g. knee pain, skin rash, fever" className="h-12 flex-1 rounded-xl border border-slate-300 px-4 text-sm" /><button onClick={() => setRecommendation(recommendDepartment(symptoms))} className="h-12 rounded-xl bg-care-600 px-5 text-sm font-black text-white">Suggest department</button></div>
        {recommendation && <div className={`mt-4 rounded-2xl border p-4 ${recommendation.emergency ? 'border-rose-300 bg-rose-50' : 'border-emerald-200 bg-emerald-50'}`} aria-live="polite"><p className={`text-xs font-black uppercase tracking-wider ${recommendation.emergency ? 'text-rose-700' : 'text-emerald-700'}`}>{recommendation.emergency ? 'Emergency warning' : 'Suggested department'}</p>{recommendation.emergency ? <><h3 className="mt-1 text-lg font-black text-rose-950">Do not wait for an OPD booking</h3><p className="mt-1 text-sm text-rose-900">Contact local emergency services or the hospital emergency desk immediately.</p><Link to="/ambulance" className="mt-3 inline-flex rounded-lg bg-rose-700 px-3 py-2 text-xs font-black text-white">Open ambulance coordination</Link></> : <><h3 className="mt-1 text-lg font-black text-emerald-950">{recommendation.department}</h3><p className="mt-1 text-sm text-emerald-900">Reason: the words entered indicate {recommendation.reason}.{recommendation.matchedKeywords.length > 0 && ` Matched: ${recommendation.matchedKeywords.join(', ')}.`}</p><p className="mt-2 text-xs font-bold text-emerald-800">A qualified clinician must confirm the appropriate care pathway.</p></>}</div>}
      </section>
      <section className="mt-6 grid gap-3 rounded-3xl border border-slate-200 bg-white p-4 shadow-sm md:grid-cols-[1fr_1fr_1.4fr_auto]">
        <label className="text-xs font-black text-slate-600">State / Union Territory<select value={state} onChange={(event) => setState(event.target.value)} className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="">All States & UTs</option>{indiaStatesAndUts.map((item) => <option key={item}>{item}</option>)}</select></label>
        <label className="text-xs font-black text-slate-600">Care group<select value={ownership} onChange={(event) => setOwnership(event.target.value as FacilityOwnership | '')} className="mt-2 h-12 w-full rounded-xl border border-slate-300 bg-white px-3 text-sm"><option value="">Government + Private</option><option value="GOVERNMENT">Government hospitals</option><option value="PRIVATE">Private hospitals</option></select></label>
        <label className="text-xs font-black text-slate-600">Hospital, city or state<div className="relative mt-2"><Search className="absolute left-3 top-3.5 size-5 text-slate-400" /><input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Try RIMS, Apollo or Ranchi" className="h-12 w-full rounded-xl border border-slate-300 pl-10 pr-3 text-sm" /></div></label>
        <button onClick={() => { setState(''); setOwnership(''); setSearch('') }} className="h-12 self-end rounded-xl border border-slate-300 px-5 text-sm font-black text-slate-700"><Filter className="mr-2 inline size-4" />Reset</button>
      </section>
      <section className="mt-8 grid gap-5 lg:grid-cols-2"><GroupLauncher title="Government hospitals" subtitle="AIIMS, RIMS, Sadar and public hospitals" count={government.length} icon={Landmark} tone="bg-emerald-50 text-emerald-700" onOpen={() => openPicker('GOVERNMENT')} /><GroupLauncher title="Private hospitals" subtitle="Apollo and other private hospital groups" count={privateFacilities.length} icon={Building2} tone="bg-violet-50 text-violet-700" onOpen={() => openPicker('PRIVATE')} /></section>
      <section className="mt-8 rounded-3xl border border-blue-100 bg-blue-50 p-5"><h2 className="font-black text-blue-950">How to use this directory</h2><ol className="mt-4 grid gap-3 text-sm text-blue-900 sm:grid-cols-3">{['Choose government or private', 'Scroll and select one hospital', 'Review departments and doctors'].map((item, index) => <li key={item} className="flex items-center gap-3 rounded-2xl bg-white p-3"><span className="grid size-8 shrink-0 place-items-center rounded-lg bg-care-600 font-black text-white">{index + 1}</span>{item}</li>)}</ol></section>
      <section className="mt-8 flex flex-col gap-4 rounded-3xl bg-ink-950 p-6 text-white sm:flex-row sm:items-center sm:justify-between"><div><h2 className="text-xl font-black">Continue directly from doctor to OPD booking</h2><p className="mt-1 text-sm text-blue-100/70">Choose a doctor profile above and SmartCare will carry the hospital, department and doctor into the booking flow.</p></div><Link to="/booking" className="inline-flex min-h-12 items-center justify-center rounded-xl bg-white px-5 text-sm font-black text-ink-950">Open OPD booking</Link></section>
    </main>

    {pickerGroup && <div className="fixed inset-0 z-[70] bg-ink-950/70 p-3 backdrop-blur-sm sm:p-6" role="dialog" aria-modal="true" aria-labelledby="hospital-picker-title"><div className="mx-auto flex h-full max-h-[92vh] w-full max-w-6xl flex-col overflow-hidden rounded-[2rem] bg-white shadow-2xl">
      <div className="flex items-start justify-between gap-4 border-b border-slate-200 p-5 sm:p-6"><div><p className="text-xs font-black uppercase tracking-[.16em] text-care-700">SmartCare hospital picker</p><h2 id="hospital-picker-title" className="mt-1 text-2xl font-black text-ink-950">{pickerGroup === 'GOVERNMENT' ? 'Government' : 'Private'} hospitals</h2><p className="mt-1 text-xs text-slate-500">Scroll the list, select a hospital, then review its project doctors.</p></div><button aria-label="Close hospital picker" onClick={() => setPickerGroup(null)} className="grid size-11 place-items-center rounded-xl border border-slate-200 text-slate-600"><X className="size-5" /></button></div>
      <div className="grid min-h-0 min-w-0 flex-1 lg:grid-cols-[22rem_minmax(0,1fr)]">
        <aside className="flex min-h-0 min-w-0 flex-col border-b border-slate-200 bg-slate-50 lg:border-b-0 lg:border-r"><div className="p-4"><div className="relative"><Search className="absolute left-3 top-3.5 size-5 text-slate-400" /><input autoFocus value={pickerSearch} onChange={(event) => setPickerSearch(event.target.value)} placeholder="Search in this group" className="h-12 w-full rounded-xl border border-slate-300 bg-white pl-10 pr-3 text-sm" /></div><p className="mt-2 text-xs font-bold text-slate-500">{pickerFacilities.length} hospitals · scroll to browse</p></div><div className="min-h-0 min-w-0 flex-1 space-y-2 overflow-y-auto px-3 pb-4">{pickerFacilities.map((facility) => <button key={`${facility.state}-${facility.name}`} onClick={() => setSelected(facility)} className={`flex w-full min-w-0 items-center gap-3 rounded-2xl border p-3 text-left transition ${selected === facility ? 'border-care-500 bg-care-50' : 'border-slate-200 bg-white hover:border-care-300'}`}><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white text-care-700"><Hospital className="size-5" /></span><span className="min-w-0"><strong className="block truncate text-sm text-ink-950">{facility.name}</strong><span className="mt-1 block truncate text-xs text-slate-500">{facility.city} · {facility.state}</span></span><ChevronRight className="ml-auto size-4 shrink-0 text-slate-400" /></button>)}</div></aside>
        <section className="min-h-0 min-w-0 overflow-y-auto p-5 sm:p-7">{selected ? <><div className="flex min-w-0 flex-col gap-4 border-b border-slate-200 pb-6 sm:flex-row sm:items-start sm:justify-between"><div className="min-w-0"><p className="text-xs font-black uppercase tracking-wider text-care-700">Selected prototype hospital</p><h3 className="mt-2 break-words text-2xl font-black text-ink-950">{selected.name}</h3><p className="mt-2 flex items-center gap-2 text-sm text-slate-600"><MapPin className="size-4 shrink-0" />{selected.city} · {selected.state}</p></div><span className={`w-fit rounded-full px-3 py-1.5 text-xs font-black ${selected.ownership === 'GOVERNMENT' ? 'bg-emerald-100 text-emerald-800' : 'bg-violet-100 text-violet-800'}`}>{selected.ownership === 'GOVERNMENT' ? 'Government group' : 'Private group'}</span></div><div className="mt-6 flex items-end justify-between gap-4"><div className="min-w-0"><p className="text-xs font-black uppercase tracking-[.15em] text-slate-500">Project doctor directory</p><h4 className="mt-1 text-xl font-black text-ink-950">Doctors and departments</h4></div><span className="shrink-0 text-xs font-bold text-slate-500">{doctors.length} profiles</span></div><div className="mt-4 grid min-w-0 gap-3 xl:grid-cols-2">{doctors.map((doctor, doctorIndex) => <article key={`${selected.name}-${doctor.name}-${doctor.department}`} className="min-w-0 rounded-2xl border border-slate-200 p-4"><div className="flex min-w-0 gap-3"><span className="grid size-11 shrink-0 place-items-center rounded-xl bg-care-50 text-care-700"><Stethoscope className="size-5" /></span><div className="min-w-0"><h5 className="break-words font-black text-ink-950">{doctor.name}</h5><p className="break-words text-xs font-bold text-care-700">{doctor.department}</p></div></div><p className="mt-3 text-sm text-slate-600">{doctor.specialty}</p><div className="mt-3 grid gap-2 text-xs sm:grid-cols-2"><p className="flex gap-1.5 text-slate-600"><IndianRupee className="size-4 shrink-0" />₹{doctor.fee.toLocaleString('en-IN')}</p><p className="flex gap-1.5 text-slate-600"><CalendarClock className="size-4 shrink-0" />{doctor.availability}</p></div>{doctor.note && <p className="mt-3 rounded-xl bg-amber-50 p-2.5 text-[11px] leading-5 text-amber-900">{doctor.note}</p>}<Link to={`/booking?facility=${selectedFacilityIndex}&prototypeDoctor=${doctorIndex}`} className="mt-4 inline-flex w-full items-center justify-center gap-2 rounded-xl bg-care-600 px-3 py-2.5 text-xs font-black text-white">Book this project OPD <ChevronRight className="size-4" /></Link></article>)}</div></> : <div className="grid min-h-64 place-items-center text-center"><div><Stethoscope className="mx-auto size-10 text-slate-300" /><p className="mt-3 font-black text-slate-600">Select a hospital to see doctors</p></div></div>}</section>
      </div>
    </div></div>}
  </div>
}

function GroupLauncher({ title, subtitle, count, icon: Icon, tone, onOpen }: { title: string; subtitle: string; count: number; icon: typeof Hospital; tone: string; onOpen: () => void }) {
  return <button onClick={onOpen} disabled={count === 0} className="group flex min-h-36 items-center gap-4 rounded-3xl border border-slate-200 bg-white p-6 text-left shadow-sm transition hover:-translate-y-0.5 hover:border-care-300 hover:shadow-md disabled:opacity-50"><span className={`grid size-14 shrink-0 place-items-center rounded-2xl ${tone}`}><Icon className="size-7" /></span><span><strong className="text-xl font-black text-ink-950">{title}</strong><span className="mt-1 block text-sm text-slate-500">{subtitle}</span><span className="mt-3 inline-flex items-center gap-1 text-xs font-black text-care-700">Open scrollable list <ChevronRight className="size-4 transition group-hover:translate-x-1" /></span></span><span className="ml-auto rounded-full bg-slate-100 px-3 py-1.5 text-xs font-black text-slate-700">{count}</span></button>
}
